import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Header from "./components/Header";
import { SurvivorsProvider } from "./contexts/SurvivorsContext";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Header />
        <SurvivorsProvider>
          <main className="flex min-h-screen flex-col items-center justify-between p-24 bg-neutral-50">
            {children}
          </main>
        </SurvivorsProvider>
      </body>
    </html>
  );
}
